import numpy as np
import pandas as pd
import os, pickle, matplotlib
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator

import ReadPeakIntensities
reload(ReadPeakIntensities)  # reload module for new changes(if any) to take effect
from ReadPeakIntensities import ReadPeakIntensities

def PlotPeakIntensities(df_peaks,first_N_peaks):
	'''
	Takes data frame of peak intensities generated by ReadPeakIntensities
	Plots first_N_peaks at the top of the data frame
	Sort the data frame by the desired feature before inputting
	By default the data frame is sorted by avg int of peaks over all frames

	example1 - process img files from scratch and sort by first frame int:
	df_peaks = ReadPeakIntensities(image_folder,header_contents,distl_params)
	df_peaks.sort_values(by=0, inplace=True, ascending=False)
	PlotPeakIntensities(df_peaks,50)

	example2 - load pickle file of the data frame from pre-processed images:
	df_peaks = pickle.load(open('...path to images/df_peaks.pickle','rb'))
	PlotPeakIntensities(df_peaks,100)
	'''
	plt.close('all')
	fig, ax = plt.subplots()
	plt.ion()

	frame_numbers = df_peaks.columns[2:-1]
	for ind in range(first_N_peaks):
		intensities = df_peaks.iloc[ind][2:-1]
		ax.plot(frame_numbers,intensities,marker='o',lw=2)

	ax.set_xlabel('Frame number',fontsize='x-large')
	ax.set_ylabel('DISTL peak intensity\n(pixel value)',fontsize='x-large')
	ax.tick_params(labelsize='large')
	ax.set_ylim(ymin = 0)
	ax.xaxis.set_minor_locator(AutoMinorLocator())
	ax.yaxis.set_minor_locator(AutoMinorLocator())
	ax.tick_params(axis='both', which='both', length=0)
	ax.grid(which='major',linewidth=0.4)
	ax.grid(which='minor',linewidth=0.2)
	ax.set_facecolor('0.95')
	for axis in ['top','bottom','left','right']: ax.spines[axis].set_visible(False)
	plt.tight_layout()
	plt.show()


image_folder = '/home/peter/Desktop/Summer_Research_2019/code/distl/images/'
header_contents = '/home/peter/Desktop/Summer_Research_2019/code/distl/header_contents.txt'
distl_params = '/home/peter/Desktop/Summer_Research_2019/code/distl/distl_params.txt'
df_peaks = ReadPeakIntensities(image_folder,header_contents,distl_params)
PlotPeakIntensities(df_peaks,50)
